import Foundation
import Testing
@testable import CampiKit

/// contract/fixtures, read straight from the repo (they're generated by tools/mock_server.py --write-fixtures).
enum Fixtures {
    static let dir = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        .appending(path: "contract/fixtures")

    static func data(_ name: String) throws -> Data { try Data(contentsOf: dir.appending(path: name)) }

    static func decode<T: Decodable>(_ type: T.Type, _ name: String) throws -> T {
        try JSONDecoder.campi.decode(T.self, from: data(name))
    }

    /// fixture file -> the contract type it holds, from contract/schema.json
    static func index() throws -> [String: String] {
        let schema = try JSONSerialization.jsonObject(
            with: Data(contentsOf: dir.deletingLastPathComponent().appending(path: "schema.json"))) as! [String: Any]
        return schema["fixtures"] as! [String: String]
    }
}

@Suite struct FixtureDecoding {
    /// Every fixture the schema lists decodes into the matching Swift type.
    @Test func everyFixtureDecodes() throws {
        let decoders: [String: (Data) throws -> Any] = [
            "Status": { try JSONDecoder.campi.decode(Status.self, from: $0) },
            "SightingPage": { try JSONDecoder.campi.decode(Page<Sighting>.self, from: $0) },
            "Sighting": { try JSONDecoder.campi.decode(Sighting.self, from: $0) },
            "Collection": { try JSONDecoder.campi.decode(LabelCollection.self, from: $0) },
            "HighlightPage": { try JSONDecoder.campi.decode(Page<Highlight>.self, from: $0) },
            "ClipList": { try JSONDecoder.campi.decode(ClipList.self, from: $0) },
            "DailyPage": { try JSONDecoder.campi.decode(Page<Daily>.self, from: $0) },
            "ArchiveList": { try JSONDecoder.campi.decode(ArchiveList.self, from: $0) },
            "Seek": { try JSONDecoder.campi.decode(Seek.self, from: $0) },
            "PairResult": { try JSONDecoder.campi.decode(PairResult.self, from: $0) },
            "Device": { try JSONDecoder.campi.decode(Device.self, from: $0) },
            "Error": { try JSONDecoder.campi.decode(ErrorEnvelope.self, from: $0) },
            "PushPayload": { data in
                let obj = try JSONSerialization.jsonObject(with: data) as! [String: Any]
                guard let info = PushInfo(userInfo: obj) else { throw APIError.decoding("push payload") }
                return info
            },
        ]
        let index = try Fixtures.index()
        #expect(index.count >= 18)
        for (file, type) in index.sorted(by: { $0.key < $1.key }) {
            let decode = try #require(decoders[type], "no Swift decoder for contract type \(type)")
            #expect(throws: Never.self, "\(file) as \(type)") { _ = try decode(Fixtures.data(file)) }
        }
    }

    @Test func status() throws {
        let s = try Fixtures.decode(Status.self, "status.json")
        #expect(s.apiVersion == 1)
        #expect(s.service.state == .running)
        #expect(s.sightings.state == .running)
        #expect(s.sightings.backend == .openvino)
        #expect(s.disk.freeGB > 0)
        #expect(s.gaming?.mode == .auto)
        #expect(s.live.mjpeg?.rawValue.hasPrefix("/live.mjpg?") == true)
        #expect(s.today == PCDay("2026-10-03"))
        #expect(s.serverTime.utcOffsetSeconds == -5 * 3600)
    }

    @Test func statusV1SightingsOffHasReservedNulls() throws {
        let s = try Fixtures.decode(Status.self, "status_v1_sightings_off.json")
        #expect(s.sightings.state == .disabled)
        #expect(s.sightings.enabled == false)
        #expect(s.sightings.backend == nil && s.sightings.cloud == nil)
        #expect(s.gaming == nil && s.clips.queue == nil)
    }

    @Test func cloudSighting() throws {
        let s = try Fixtures.decode(Sighting.self, "sighting_cloud.json")
        #expect(s.decidedBy == .cloud)
        #expect(s.machine.source == .cloud)
        #expect(s.siglip.label != s.label)
        #expect(s.yearRange != nil && s.color != nil)
        #expect(s.media.crop != nil)
        #expect(s.midpoint >= s.startedAt.date && s.midpoint <= s.endedAt.date)
    }

    @Test func correctedSighting() throws {
        let s = try Fixtures.decode(Sighting.self, "sighting_corrected.json")
        #expect(s.decidedBy == .user)
        #expect(s.correction?.label == s.label)
        #expect(s.machine.label != s.label)
    }

    @Test func highlightContentKinds() throws {
        let page = try Fixtures.decode(Page<Highlight>.self, "highlights_page.json")
        var kinds = Set<String>()
        for h in page.items {
            switch h.content {
            case .sighting: kinds.insert("sighting")
            case .clip: kinds.insert("clip")
            case .daily: kinds.insert("daily")
            case .window(_, let clip): kinds.insert(clip == nil ? "window-expired" : "window")
            case .unknown: Issue.record("unknown highlight content \(h.id)")
            }
        }
        #expect(kinds.isSuperset(of: ["sighting", "clip", "daily", "window-expired"]))
        #expect(page.items.contains { $0.types == [.newCatch, .rare] })
    }

    @Test func collection() throws {
        let c = try Fixtures.decode(LabelCollection.self, "collection.json")
        #expect(c.caught == c.items.filter(\.isCaught).count)
        #expect(c.items.contains { $0.origin == .discovered })
        #expect(c.items.contains { $0.tier == .uncaught && $0.cover == nil })
        #expect(c.tiers.map(\.tier) == [.rare, .uncommon, .common])
    }

    @Test func timelapse() throws {
        let clips = try Fixtures.decode(ClipList.self, "clips.json")
        #expect(clips.items.first?.duration != nil)
        #expect(clips.latestId == clips.items.first?.id)
        let archive = try Fixtures.decode(ArchiveList.self, "archive.json")
        #expect(archive.items.filter(\.current).allSatisfy { $0.media.video == nil })
        let seekClip = try Fixtures.decode(Seek.self, "seek_clip.json")
        #expect(seekClip.target == .clip && seekClip.offset != nil && !seekClip.approximate)
        let seekDaily = try Fixtures.decode(Seek.self, "seek_daily.json")
        #expect(seekDaily.target == .daily && seekDaily.approximate)
        let seekNone = try Fixtures.decode(Seek.self, "seek_none.json")
        #expect(seekNone.target == .none && seekNone.reason == .noFrames && seekNone.video == nil)
    }

    @Test func pushPayloads() throws {
        let catchObj = try JSONSerialization.jsonObject(with: Fixtures.data("push_new_catch.json")) as! [String: Any]
        let info = try #require(PushInfo(userInfo: catchObj))
        #expect(info.type == .newCatch && info.sightingId != nil && info.crop != nil)
        let svcObj = try JSONSerialization.jsonObject(with: Fixtures.data("push_service.json")) as! [String: Any]
        let svc = try #require(PushInfo(userInfo: svcObj))
        #expect(svc.type == .service && svc.alert == .captureDisconnected && svc.sightingId == nil)
    }
}

@Suite struct Tolerance {
    @Test func unknownEnumValuesDecodeAsUnknown() throws {
        var obj = try JSONSerialization.jsonObject(with: Fixtures.data("status.json")) as! [String: Any]
        var sightings = obj["sightings"] as! [String: Any]
        sightings["state"] = "warp_speed"
        sightings["phase"] = "dreaming"
        obj["sightings"] = sightings
        obj["brand_new_key"] = ["anything": 1]
        let s = try JSONDecoder.campi.decode(Status.self, from: JSONSerialization.data(withJSONObject: obj))
        #expect(s.sightings.state == .unknown)
        #expect(s.sightings.phase == .unknown)
    }

    @Test func missingReservedKeysAreNil() throws {
        var obj = try JSONSerialization.jsonObject(with: Fixtures.data("status.json")) as! [String: Any]
        obj.removeValue(forKey: "gaming")
        let s = try JSONDecoder.campi.decode(Status.self, from: JSONSerialization.data(withJSONObject: obj))
        #expect(s.gaming == nil)
    }
}
